error: Rename 'generic_error' to 'unknown_error'
Leaving old value for now so this doesn't break on pull-through.

Change-Id: I90c30ba63e7372ba4a533261f1789517fe19dcb8